# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivegame',
            name='team_second',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='football.Team'),
        ),
        migrations.AlterField(
            model_name='archivegame',
            name='team_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='football.Team'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 11, 33, 58, 194305, tzinfo=utc)),
        ),
    ]
